algoritmo "Operadores relacionais"
var
A, B, C: inteiro
inicio
A <- 2
B <- 3
C <- 5
Escreval("A > B?", A > B)
Escreval("A = B?", A = B)
Escreval("A <> B?",A <> B)
Escreval("A > 2?" ,A > 2)
Escreval("A >= 2?", A >= 2)
Escreval("C = A + B?", C = A + B)
Escreval("C >= B ^ A?", C >= B ^ A)
Escreval("C <= B ^ A?", C <= B ^ A)
Escreval("B <= C % 2?", B <= C % 2)
Escreval("1 = C % 2?", 1 = C % 2)
fimalgoritmo