algoritmo "Quarto"
var
a, b: inteiro
inicio
escreva("Digite um número: ")
leia(a)
escreva("Digite outro número: ")
leia(b)
EscrevaL("")
escreval("A soma é:", a + b)
escreval("A subtração é:", a - b)
escreval("A multiplicação é:", a * b)
escreval("A divisão é:", a / b)
escreval("A divisão inteira é:", a \ b)
escreval("A potênciação é:", a ^ b)
escreval("O resto é:", a % b)
EscrevaL("")
escreval("Ordem de precedência")
escreval(3 + 2 / 2)
escreva((3 + 2) / 2)
fimalgoritmo